version: "3.3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - .data/mysql:/var/lib/mysql
  redis:
    image: redis:6-alpine
    restart: always
    command: ["redis-server", "--requirepass", "foobar"]
    ports:
      - 6379:6379
