mybatis:
  type-aliases-package: com.github.candyacao.model

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      additional-path: com.github.candyacao
logging:
  level:
    com:
      github:
        candyacao: TRACE
